apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.name}}-primary
  labels:
    app: {{.Values.name}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{.Values.name}}.com
    http:
      paths:
      - backend:
          #serviceName: ${k8s.primaryServiceName}
          serviceName: {{.Values.name}}-primary
          servicePort: 80
